# Generated by Django 4.1.1 on 2022-11-06 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculatorapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.FloatField(blank=True, default='', null=True),
        ),
    ]
